/// <summary>
/// Tarea 2b_A
/// </summary>


<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ciclos [

<!ELEMENT ciclos (ciclo)>

<!ELEMENT ciclo ((medio | superior)*, familia, codigo, nome)>

<!ELEMENT medio EMPTY>
<!ELEMENT superior EMPTY>

<!ELEMENT familia (#PCDATA)>

<!ELEMENT codigo (#PCDATA)>

<!ELEMENT nome (#PCDATA)>

]>


<ciclos>

<ciclo>

<superior />

<familia>Informática e comunicacións</familia>

<codigo>CSIFC03</codigo>

<nome>Desenvolvemento de aplicacións web</nome>
        

</ciclo>

<ciclo>

<medio />

<familia>Madeira, Moble e Cortiza</familia>

<codigo>CMMMC01</codigo>

<nome>Carpintaría e Moble</nome>

</ciclo>

</ciclos>












/// <summary>
/// Tarea 2b_B
/// </summary>


<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE paises [

<!ELEMENT paises (pais)>

<!ELEMENT pais (nome, continente*, G20?, oceano*)>

<!ELEMENT nome (#PCDATA)>

<!ELEMENT G20 EMPTY>

<!ELEMENT continente (#PCDATA)>

<!ELEMENT oceano (#PCDATA)>

]>

<paises>

<pais>

<nome>Sudáfrica</nome>

<continente>Africa</continente>

<G20 />

<oceano>Atlántico</oceano>

<oceano>Indico</oceano>

</pais>

<pais>

<nome>Colombia</nome>

<continente>América</continente>

<oceano>Atlántico</oceano>

<oceano>Pacífico</oceano>

</pais>

<pais>

<nome>Bolivia</nome>

<continente>América</continente>

</pais>

<pais>

<nome>India</nome>

<continente>Asia</continente>

<G20 />

<oceano>Indico</oceano>

</pais>

</paises>




















/// <summary>
/// Tarea 2b_C
/// </summary>


<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE alumnos [

<!ELEMENT alumnos (alumno)>

<!ELEMENT alumno (numeroExpediente+ , dataNacimiento, nome, telefono+)>

<!ELEMENT numeroExpedente (#PCDATA)>

<!ELEMENT dataNacemento (#PCDATA)>

<!ELEMENT nome (#PCDATA)>

<!ELEMENT telefono (#PCDATA)>

]>

<alumnos>

<alumno>

<numeroExpedente>1023</numeroExpedente>

<nome>Alba Prado</nome>

<dataNacemento>25/04/1984</dataNacemento>

<telefono>676767676</telefono>

<telefono>999888777</telefono>

<muller />

</alumno>

<alumno>

<numeroExpedente>1444</numeroExpedente>

<nome>Brais Seoane</nome>

<dataNacemento>10/04/1985</dataNacemento>

<telefono>688668866</telefono>

<varon />

</alumno>

</alumnos>


























/// <summary>
/// Tarea 2b_D
/// </summary>

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE datasImportantes [

<!ELEMENT datasImportantes (cumpleanos,aniversarioBoda)>

<!ELEMENT aniversarioBoda (persoa, data)>

<!ELEMENT cumpleanos (persoa, data)>

<!ELEMENT persoa (#PCDATA)>

<!ELEMENT data (mes,dia)>

<!ELEMENT mes (#PCDATA)>

<!ELEMENT dia (#PCDATA)>

]>

<datasImportantes>

<cumpleanos>

<persoa>Marta</persoa>

<data>

<mes>Xullo</mes>

<dia>14</dia>

</data>

</cumpleanos>

<cumpleanos>

<persoa>Marga</persoa>

<data>

<mes>Maio</mes>

<dia>10</dia>

</data>

</cumpleanos>

<cumpleanos>

<persoa>Xurxo</persoa>

<data>

<mes>Xaneiro</mes>

<dia>9</dia>

</data>

</cumpleanos>

<aniversarioBoda>

<data>

<mes>Setembro</mes>

<dia>30</dia>

</data>

</aniversarioBoda>

</datasImportantes>

























/// <summary>
/// Tarea 2b_E
/// </summary>

Neste caso completa o DTD para que o documento XML sexa válido:

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE nota[
<!ELEMENT nota (acronimo, ingles)>
<!ELEMENT acronimo (#PCDATA)>
<!ELEMENT ingles (#PCDATA)>
]>

<nota>A linguaxe <acronimo>XML</acronimo>

ou <ingles>Extensible Markup Language</ingles>

é un subconxunto de <acronimo>SGML</acronimo>

que ten como propósito principal facilitar a transferencia

de datos a través de diferentes plataformas,

especialmente as conectadas a Internet

</nota>