=== LaureDSD/CODE-2/U1/DTD/email.dtd
<!DOCTYPE mensaxe SYSTEM "mensaje.dtd" [
<!ELEMENT mensaxe(de , para+ , asunto , adxunto* , corpo?)>
    <!ELEMENT de (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    <!ELEMENT adxunto (#MIXED)>
    <!ELEMENT corpo (#PCDATA)>
]

=== LaureDSD/CODE-2/U1/DTD/tarea3.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="yes" ?>

<!DOCTYPE mensaxre [

<!ELEMENT mensaxe(de , para+ , asunto , adxunto* , corpo?)>

    <!ELEMENT de (#PCDATA)>
    <!ELEMENT para (#PCDATA)>
    <!ELEMENT asunto (#PCDATA)>
    
    <!ELEMENT adxunto (#MIXED)>
    <!ELEMENT corpo (#PCDATA)>

    <!ATTLIST mensaxe prioridad CDATA 'normal'>
    <!ATTLIST mensaxe gardarBandexa CDATA 'enviados'>

]>


<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE mensaxe SYSTEM "email.dtd">




<mensaxe prioridad='urgente' gardarBandexa='enviados'>

<de>maria@gmail.com</de>

<para>ignacio@gmail.com</para>

<para>pedro@edu.xunta.es</para>

<asunto>Env√≠oche os arquivos</asunto>

<adxunto>D:\fotos\dePesca.jpg</adxunto>

<adxunto>D:\docs\carta.odt</adxunto>

<adxunto>D:\fotos\naCea.jpg</adxunto>

</mensaxe>
