Comproba se os seguintes documentos son válidos e en caso contrario modifica o XML para que responda á DTD proposta.

a) Tarefa4a_a.xml

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE exames [

<!ELEMENT exames (examen*)>

<!ELEMENT examen #CDATA>

<!ATTLIST examen data CDATA #REQUIRED>

<!ATTLIST examen hora CDATA #REQUIRED>

<!ATTLIST examen materia CDATA #REQUIRED>

]>

<exames>

<examen data="15/02/2012" hora="18:30" materia="Bases de datos"></examen>

<examen data="06/03/2012" hora="16:00" materia="XML"></examen>

<examen data="30/03/2012" hora="19:00" materia="Redes"></examen>

</exames>


















b) Tarefa4a_b

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE alumnos [

<!ELEMENT alumnos (alumno*)>

<!ELEMENT alumno EMPTY>

<!ATTLIST alumno codigo ID #REQUIRED>

<!ATTLIST alumno nome CDATA #REQUIRED>

<!ATTLIST alumno idade CDATA #REQUIRED>

]>

<alumnos>

<alumno codigo="100" nome="Lorena Casal Rodríguez" idade="5" />

<alumno codigo="123" nome="Xurxo Vega Sousa" idade="7" />

<alumno codigo="132" nome="Antía Castro Castiñeira" idade="7"/>

</alumnos>



















c) Tarefa4a_c

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE material [

<!ELEMENT material (articulo*)>

<!ELEMENT articulo EMPTY>

<!ATTLIST articulo nome CDATA #REQUIRED>

<!ATTLIST articulo cantidade CDATA "1">

]>


<material>
<articulo nome="caderno" cantidade="2" />

<articulo nome="boli" cantidade="2" />

<articulo nome="goma" cantidade="3" />

<articulo nome="regra" />    

</material>




















Tarefa 4_b. Modificación de DTDs para que validen documentos XML con atributos.

Corrixe os erros que se atopan nas seguintes DTDs e comproba co editor de XML que xa son documentos válidos. Inda que pode haber máis dunha solución para cada unha das tarefas, tenta encontrar a máis sinxela.

a) Tarefa4b_a.xml


<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE exames [

<!ELEMENT exames (examen+)>

<!ELEMENT examen (#PCDATA)>

<!ATTLIST examen data CDATA #REQUIRED>

<!ATTLIST examen hora CDATA #REQUIRED>

]>

<exames>

<examen data="15/02/2012" hora="18:30">Bases de datos</examen>

<examen data="06/03/2012" hora="16:00">XML</examen>

<examen data="30/03/2012" hora="19:00">Redes</examen>

</exames>









b) Tarefa4b_b.xml



<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE departamento [

<!ELEMENT departamento EMPTY>

<!ATTLIST departamento nome CDATA #REQUIRED>

 <!ATTLIST departamento xefe CDATA>

]>

<departamento nome="Electricidade e electrónica" />











c) Tarefa4b_c.xml

<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE provincias [

<!ELEMENT provincias (provincia+)>

<!ELEMENT provincia EMPTY>

<!ATTLIST provincia codigo ID #REQUIRED>

<!ATTLIST provincia nome CDATA #REQUIRED>

<!ATTLIST provincia rexion CDATA #REQUIRED>

]>

<provincias>

<provincia codigo="27" nome="Lugo" rexion="Galicia" />

<provincia codigo="32" nome="Ourense" rexion="Galicia" />

<provincia codigo="36" nome="Pontevedra" rexion="Galicia" />

</provincias>










d) Tarefa4b_d.xml

?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE instituto [

<!ELEMENT instituto (ciclo*, alumno*)>

<!ELEMENT ciclo EMPTY>

<!ATTLIST ciclo codigo ID #REQUIRED>

<!ATTLIST ciclo nome CDATA #REQUIRED>

<!ATTLIST ciclo grao (medio | superior) #IMPLIED>


<!ELEMENT alumno EMPTY>

<!ATTLIST alumno nome CDATA #REQUIRED>

<!ATTLIST alumno ciclo CDATA #IMPLIED>



]>



<instituto>

<ciclo codigo="CSIFC01" nome="ASIR" grao="superior"/>

<ciclo codigo="CSIFC02" nome="DAM" />

<alumno nome="Alejandro Maceda Barros" ciclo="ASIR" />

<alumno nome="Mar Maceda Abel" ciclo="ASIR" />

<alumno nome="Carolina Castiñeira Lamas" ciclo="DAM" />

<alumno nome="Mauro Varela Vila" ciclo="DAM" />

</instituto>